import { productImages, productDetailImages } from './images';
import { Product } from '../types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Nike Air Max 270',
    description: 'Experience ultimate comfort with the Nike Air Max 270. The large Air unit delivers unrivaled cushioning with every step.',
    price: 150.00,
    images: productDetailImages.nikeAirMax,
    category: 'Running',
    brand: 'Nike',
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: ['Black', 'White', 'Red'],
    rating: 4.5,
    reviews: 128,
    inStock: true,
  },
  {
    id: '2',
    name: 'Adidas Superstar',
    description: 'Classic design meets modern comfort in the Adidas Superstar. The iconic shell toe design provides both style and protection.',
    price: 120.00,
    images: productDetailImages.adidasSuperstar,
    category: 'Lifestyle',
    brand: 'Adidas',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['Black', 'White', 'Blue'],
    rating: 4.8,
    reviews: 256,
    inStock: true,
  },
  {
    id: '3',
    name: 'Puma RS-X',
    description: 'Bold design and superior comfort in the Puma RS-X. The chunky silhouette and retro-inspired design make a statement.',
    price: 130.00,
    images: productDetailImages.pumaRSX,
    category: 'Sports',
    brand: 'Puma',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['Black', 'White', 'Green'],
    rating: 4.6,
    reviews: 192,
    inStock: true,
  },
  {
    id: '4',
    name: 'New Balance 574',
    description: 'Classic heritage design with modern comfort technology. The New Balance 574 offers timeless style and all-day comfort.',
    price: 110.00,
    images: productDetailImages.newBalance574,
    category: 'Lifestyle',
    brand: 'New Balance',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['Grey', 'Navy', 'Red'],
    rating: 4.7,
    reviews: 156,
    inStock: true,
  },
  {
    id: '5',
    name: 'Nike Zoom Fly 5',
    description: 'Professional running shoes with responsive cushioning and lightweight design. Perfect for marathon training and racing.',
    price: 160.00,
    images: productDetailImages.nikeZoomFly,
    category: 'Running',
    brand: 'Nike',
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: ['Black', 'Blue', 'White'],
    rating: 4.9,
    reviews: 89,
    inStock: true,
  },
  {
    id: '6',
    name: 'Adidas Ultra Boost',
    description: 'Premium comfort with Boost technology. The Ultra Boost provides exceptional energy return and cushioning.',
    price: 180.00,
    images: productDetailImages.adidasUltraBoost,
    category: 'Running',
    brand: 'Adidas',
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: ['Black', 'White', 'Grey'],
    rating: 4.8,
    reviews: 245,
    inStock: true,
  },
  {
    id: '7',
    name: 'Puma Suede Classic',
    description: 'Iconic street style with the Puma Suede Classic. The timeless design and comfortable fit make it perfect for everyday wear.',
    price: 85.00,
    images: productDetailImages.pumaSuede,
    category: 'Lifestyle',
    brand: 'Puma',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['Black', 'White', 'Red'],
    rating: 4.6,
    reviews: 178,
    inStock: true,
  },
  {
    id: '8',
    name: 'New Balance Fresh Foam 1080v12',
    description: 'Maximum comfort with Fresh Foam technology. The 1080v12 offers plush cushioning for long-distance running.',
    price: 160.00,
    images: productDetailImages.newBalance1080,
    category: 'Running',
    brand: 'New Balance',
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: ['Grey', 'Blue', 'Black'],
    rating: 4.7,
    reviews: 134,
    inStock: true,
  },
  {
    id: '9',
    name: 'Nike Dunk Low',
    description: 'Classic basketball-inspired design with modern comfort. The Dunk Low is perfect for both style and performance.',
    price: 110.00,
    images: productDetailImages.nikeDunk,
    category: 'Lifestyle',
    brand: 'Nike',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['Black', 'White', 'Green'],
    rating: 4.5,
    reviews: 167,
    inStock: true,
  },
  {
    id: '10',
    name: 'Adidas Stan Smith',
    description: 'Timeless tennis-inspired design with modern comfort. The Stan Smith is a versatile shoe for any occasion.',
    price: 95.00,
    images: productDetailImages.adidasStanSmith,
    category: 'Lifestyle',
    brand: 'Adidas',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['White', 'Green', 'Black'],
    rating: 4.6,
    reviews: 189,
    inStock: true,
  },
  {
    id: '11',
    name: 'Nike Air Jordan 1',
    description: 'Iconic basketball sneaker with premium leather upper and Air cushioning. A timeless classic that never goes out of style.',
    price: 170.00,
    images: productDetailImages.nikeAirMax,
    category: 'Lifestyle',
    brand: 'Nike',
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: ['Black', 'Red', 'White'],
    rating: 4.9,
    reviews: 312,
    inStock: true,
  },
  {
    id: '12',
    name: 'Adidas Yeezy Boost 350',
    description: 'Revolutionary design with Primeknit upper and Boost cushioning. The Yeezy Boost 350 offers unmatched comfort and style.',
    price: 220.00,
    images: productDetailImages.adidasSuperstar,
    category: 'Lifestyle',
    brand: 'Adidas',
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: ['Black', 'White', 'Grey'],
    rating: 4.8,
    reviews: 289,
    inStock: true,
  },
  {
    id: '13',
    name: 'Puma Future Rider',
    description: 'Retro-inspired design with modern comfort technology. The Future Rider combines classic style with contemporary performance.',
    price: 100.00,
    images: productDetailImages.pumaRSX,
    category: 'Lifestyle',
    brand: 'Puma',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['Black', 'White', 'Blue'],
    rating: 4.6,
    reviews: 145,
    inStock: true,
  },
  {
    id: '14',
    name: 'New Balance 327',
    description: 'Heritage-inspired design with modern comfort. The 327 offers a perfect blend of retro style and contemporary performance.',
    price: 100.00,
    images: productDetailImages.newBalance574,
    category: 'Lifestyle',
    brand: 'New Balance',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['Grey', 'Navy', 'Red'],
    rating: 4.7,
    reviews: 167,
    inStock: true,
  },
  {
    id: '15',
    name: 'Nike Air Force 1',
    description: 'Classic basketball sneaker with premium leather upper. The Air Force 1 is a timeless icon of street style.',
    price: 110.00,
    images: productDetailImages.nikeZoomFly,
    category: 'Lifestyle',
    brand: 'Nike',
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: ['White', 'Black', 'Red'],
    rating: 4.8,
    reviews: 234,
    inStock: true,
  },
  {
    id: '16',
    name: 'Adidas Samba',
    description: 'Classic indoor soccer shoe with premium suede upper. The Samba offers timeless style and versatile performance.',
    price: 90.00,
    images: productDetailImages.adidasUltraBoost,
    category: 'Lifestyle',
    brand: 'Adidas',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['Black', 'White', 'Green'],
    rating: 4.6,
    reviews: 178,
    inStock: true,
  },
  {
    id: '17',
    name: 'Puma Cali',
    description: 'Modern take on classic California style. The Cali offers premium comfort and contemporary design.',
    price: 95.00,
    images: productDetailImages.pumaSuede,
    category: 'Lifestyle',
    brand: 'Puma',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['White', 'Black', 'Pink'],
    rating: 4.5,
    reviews: 123,
    inStock: true,
  },
  {
    id: '18',
    name: 'New Balance 997H',
    description: 'Heritage-inspired design with modern comfort. The 997H offers premium style and all-day comfort.',
    price: 120.00,
    images: productDetailImages.newBalance1080,
    category: 'Lifestyle',
    brand: 'New Balance',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['Grey', 'Navy', 'Red'],
    rating: 4.7,
    reviews: 156,
    inStock: true,
  },
  {
    id: '19',
    name: 'Nike Blazer Mid',
    description: 'Classic basketball sneaker with premium leather upper. The Blazer Mid offers timeless style and versatile performance.',
    price: 100.00,
    images: productDetailImages.nikeDunk,
    category: 'Lifestyle',
    brand: 'Nike',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['White', 'Black', 'Red'],
    rating: 4.6,
    reviews: 189,
    inStock: true,
  },
  {
    id: '20',
    name: 'Adidas Forum Low',
    description: 'Classic basketball sneaker with premium leather upper. The Forum Low offers timeless style and versatile performance.',
    price: 100.00,
    images: productDetailImages.adidasStanSmith,
    category: 'Lifestyle',
    brand: 'Adidas',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['White', 'Black', 'Blue'],
    rating: 4.7,
    reviews: 167,
    inStock: true,
  },
]; 